name: Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - "**/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        id: build
        uses: ./.github/actions/build

      - name: Deploy
        id: deploy
        if: success()
        uses: ./.github/actions/deploy
        with:
          ssh_private_key: ${{ vars.SSH_PRIVATE_KEY }}
          remote_host: ${{ vars.REMOTE_HOST }}
          remote_user: ${{ vars.REMOTE_USER }}
          target: ${{ vars.TARGET }}

      - name: Pull
        id: pull
        if: success()
        uses: ./.github/actions/pull
        with:
          ssh_private_key: ${{ vars.SSH_PRIVATE_KEY }}
          remote_host: ${{ vars.REMOTE_HOST }}
          remote_user: ${{ vars.REMOTE_USER }}
          target: ${{ vars.TARGET }}
          branch: main
